# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
#  sf_guard_plugin:
#    profile_class: Ficha
#    profile_field_name: usuario_id
  estados:
    Alumno:
      Preinscripto: 0
      Inscripto: 1
      Expulsado: 2
      Abandono: 3
      "Cambio de instituto": 4
      Rechazado: 5
      Egresado: 6
    AlumnoBaja:
      Expulsado: 2
      Abandono: 3
      "Cambio de instituto": 4
      Rechazado: 5
      Egresado: 6
    Docente:
      Activo: 0
      "Con Licencia": 1
      "Cargo de mayor jerarquía": 2
      Renuncia: 3
      "Cesantía": 4
      Disponibilidad: 5
      "Jubilación": 6
      "Tareas pasivas": 7
    DocenteBaja:
      "Con Licencia": 1
      "Cargo de mayor jerarquía": 2
      Renuncia: 3
      "Cesantía": 4
      Disponibilidad: 5
      "Jubilación": 6
      "Tareas pasivas": 7

    Carrera:
      Vigente: 0
      "Cambio de currícula": 1
      "Resolución Ministerial": 2
      "Falta de alumnos": 3
    CarreraBaja:
      "Cambio de currícula": 1
      "Resolución Ministerial": 2
      "Falta de alumnos": 3
