# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:
all:
#  sf_guard_plugin:
#    profile_class: Ficha
#    profile_field_name: usuario_id
  estados:
    Alumno:
      preinscripto: 0
      inscripto: 1
      expulsado: 2
      abandono: 3
      cambio_de_instituto: 4
      rechazado: 5
      egresado: 6
    AlumnoBaja:
      expulsado: 2
      abandono: 3
      cambio_de_instituto: 4
      rechazado: 5
      egresado: 6
    Docente:
      suplente: 0
      interino: 1
      titular: 2
