generator:
  class: sfPropelGenerator
  param:
    model_class:           Alumno
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Alumno
    plural:                Alumnos
    route_prefix:          alumno
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [ _id, _nombre, _documento, _carrera, _estado ]
        batch_actions: {}
      filter:
        display: [ nombre, nro_documento, carrera, estado, beca ]
      form:    ~
      edit:    ~
      new:     ~
