generator:
  class: sfPropelGenerator
  param:
    model_class:           Docente
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Docente
    plural:                Docentes
    route_prefix:          docente
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        display: [ id, _nombre, _documento, _carrera, _estado ]
        batch_actions: {}
      filter:  
        display: [ nombre, nro_documento, carrera, estado ]
      form:    ~
      edit:    ~
      new:     ~
