generator:
  class: sfPropelGenerator
  param:
    model_class:           Carrera
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Carrera
    plural:                Carreras
    route_prefix:          carrera
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ _id, _nombre, _estado, _creada, _creada_por ]
        batch_actions: {}
      filter:
        display: [ id, estado ]
      form:    ~
      edit:    ~
      new:     ~
